
DELETE rp FROM role_permissions rp JOIN permissions p ON p.id = rp.permission_id WHERE p.code IN ('customers.view.all', 'customers.create.all', 'customers.update.all', 'customers.delete.all', 'locations.view.all', 'locations.create.all', 'locations.update.all', 'locations.delete.all', 'surveyors.view.all', 'surveyors.create.all', 'surveyors.update.all', 'surveyors.delete.all', 'surveyors.manage.all', 'container_types.view.all', 'container_types.create.all', 'container_types.update.all', 'container_types.delete.all', 'survey_types.view.all', 'survey_types.create.all', 'survey_types.update.all', 'survey_types.delete.all', 'cedex_locations.view.all', 'cedex_locations.create.all', 'cedex_locations.update.all', 'cedex_locations.delete.all', 'cedex_locations.manage.all', 'cedex_components.view.all', 'cedex_components.create.all', 'cedex_components.update.all', 'cedex_components.delete.all', 'cedex_components.manage.all', 'cedex_damages.view.all', 'cedex_damages.create.all', 'cedex_damages.update.all', 'cedex_damages.delete.all', 'cedex_damages.manage.all', 'cedex_repairs.view.all', 'cedex_repairs.create.all', 'cedex_repairs.update.all', 'cedex_repairs.delete.all', 'cedex_repairs.manage.all', 'cedex_materials.view.all', 'cedex_materials.create.all', 'cedex_materials.update.all', 'cedex_materials.delete.all', 'cedex_materials.manage.all', 'responsibility_codes.view.all', 'responsibility_codes.create.all', 'responsibility_codes.update.all', 'responsibility_codes.delete.all', 'responsibility_codes.manage.all');

DELETE FROM permissions WHERE code IN ('customers.view.all', 'customers.create.all', 'customers.update.all', 'customers.delete.all', 'locations.view.all', 'locations.create.all', 'locations.update.all', 'locations.delete.all', 'surveyors.view.all', 'surveyors.create.all', 'surveyors.update.all', 'surveyors.delete.all', 'surveyors.manage.all', 'container_types.view.all', 'container_types.create.all', 'container_types.update.all', 'container_types.delete.all', 'survey_types.view.all', 'survey_types.create.all', 'survey_types.update.all', 'survey_types.delete.all', 'cedex_locations.view.all', 'cedex_locations.create.all', 'cedex_locations.update.all', 'cedex_locations.delete.all', 'cedex_locations.manage.all', 'cedex_components.view.all', 'cedex_components.create.all', 'cedex_components.update.all', 'cedex_components.delete.all', 'cedex_components.manage.all', 'cedex_damages.view.all', 'cedex_damages.create.all', 'cedex_damages.update.all', 'cedex_damages.delete.all', 'cedex_damages.manage.all', 'cedex_repairs.view.all', 'cedex_repairs.create.all', 'cedex_repairs.update.all', 'cedex_repairs.delete.all', 'cedex_repairs.manage.all', 'cedex_materials.view.all', 'cedex_materials.create.all', 'cedex_materials.update.all', 'cedex_materials.delete.all', 'cedex_materials.manage.all', 'responsibility_codes.view.all', 'responsibility_codes.create.all', 'responsibility_codes.update.all', 'responsibility_codes.delete.all', 'responsibility_codes.manage.all');






