-- 0017_container_fitness_master_stage2_permissions.sql
-- Align granular CRUD permissions for Admin Master Data CRUD Stage 2.
-- Safe to run repeatedly after 0015_container_fitness_foundation.sql and 0016_container_fitness_master_stage1_permissions.sql.

START TRANSACTION;

INSERT IGNORE INTO permissions (code, name, module, action, scope, description)
VALUES
  ('maintenance_schemes.view.all', 'View Maintenance Schemes', 'maintenance_schemes', 'view', 'all', 'Melihat skema pemeliharaan peti kemas'),
  ('maintenance_schemes.create.all', 'Create Maintenance Schemes', 'maintenance_schemes', 'create', 'all', 'Membuat skema pemeliharaan peti kemas'),
  ('maintenance_schemes.update.all', 'Update Maintenance Schemes', 'maintenance_schemes', 'update', 'all', 'Mengubah skema pemeliharaan peti kemas'),
  ('maintenance_schemes.delete.all', 'Delete Maintenance Schemes', 'maintenance_schemes', 'delete', 'all', 'Menonaktifkan skema pemeliharaan peti kemas'),
  ('inspection_areas.view.all', 'View Inspection Areas', 'inspection_areas', 'view', 'all', 'Melihat area pemeriksaan peti kemas'),
  ('inspection_areas.create.all', 'Create Inspection Areas', 'inspection_areas', 'create', 'all', 'Membuat area pemeriksaan peti kemas'),
  ('inspection_areas.update.all', 'Update Inspection Areas', 'inspection_areas', 'update', 'all', 'Mengubah area pemeriksaan peti kemas'),
  ('inspection_areas.delete.all', 'Delete Inspection Areas', 'inspection_areas', 'delete', 'all', 'Menonaktifkan area pemeriksaan peti kemas'),
  ('structural_components.view.all', 'View Structural Components', 'structural_components', 'view', 'all', 'Melihat komponen struktur peti kemas'),
  ('structural_components.create.all', 'Create Structural Components', 'structural_components', 'create', 'all', 'Membuat komponen struktur peti kemas'),
  ('structural_components.update.all', 'Update Structural Components', 'structural_components', 'update', 'all', 'Mengubah komponen struktur peti kemas'),
  ('structural_components.delete.all', 'Delete Structural Components', 'structural_components', 'delete', 'all', 'Menonaktifkan komponen struktur peti kemas'),
  ('structural_damage_criteria.view.all', 'View Structural Damage Criteria', 'structural_damage_criteria', 'view', 'all', 'Melihat kriteria kerusakan struktur'),
  ('structural_damage_criteria.create.all', 'Create Structural Damage Criteria', 'structural_damage_criteria', 'create', 'all', 'Membuat kriteria kerusakan struktur'),
  ('structural_damage_criteria.update.all', 'Update Structural Damage Criteria', 'structural_damage_criteria', 'update', 'all', 'Mengubah kriteria kerusakan struktur'),
  ('structural_damage_criteria.delete.all', 'Delete Structural Damage Criteria', 'structural_damage_criteria', 'delete', 'all', 'Menonaktifkan kriteria kerusakan struktur'),
  ('finding_severities.view.all', 'View Finding Severities', 'finding_severities', 'view', 'all', 'Melihat tingkat temuan'),
  ('finding_severities.create.all', 'Create Finding Severities', 'finding_severities', 'create', 'all', 'Membuat tingkat temuan'),
  ('finding_severities.update.all', 'Update Finding Severities', 'finding_severities', 'update', 'all', 'Mengubah tingkat temuan'),
  ('finding_severities.delete.all', 'Delete Finding Severities', 'finding_severities', 'delete', 'all', 'Menonaktifkan tingkat temuan'),
  ('inspection_test_parameters.view.all', 'View Inspection Test Parameters', 'inspection_test_parameters', 'view', 'all', 'Melihat parameter pengujian kelaikan'),
  ('inspection_test_parameters.create.all', 'Create Inspection Test Parameters', 'inspection_test_parameters', 'create', 'all', 'Membuat parameter pengujian kelaikan'),
  ('inspection_test_parameters.update.all', 'Update Inspection Test Parameters', 'inspection_test_parameters', 'update', 'all', 'Mengubah parameter pengujian kelaikan'),
  ('inspection_test_parameters.delete.all', 'Delete Inspection Test Parameters', 'inspection_test_parameters', 'delete', 'all', 'Menonaktifkan parameter pengujian kelaikan'),
  ('fitness_checklist_templates.view.all', 'View Fitness Checklist Templates', 'fitness_checklist_templates', 'view', 'all', 'Melihat template checklist kelaikan'),
  ('fitness_checklist_templates.create.all', 'Create Fitness Checklist Templates', 'fitness_checklist_templates', 'create', 'all', 'Membuat template checklist kelaikan'),
  ('fitness_checklist_templates.update.all', 'Update Fitness Checklist Templates', 'fitness_checklist_templates', 'update', 'all', 'Mengubah template checklist kelaikan'),
  ('fitness_checklist_templates.delete.all', 'Delete Fitness Checklist Templates', 'fitness_checklist_templates', 'delete', 'all', 'Menonaktifkan template checklist kelaikan'),
  ('evidence_photo_categories.view.all', 'View Evidence Photo Categories', 'evidence_photo_categories', 'view', 'all', 'Melihat kategori foto evidence'),
  ('evidence_photo_categories.create.all', 'Create Evidence Photo Categories', 'evidence_photo_categories', 'create', 'all', 'Membuat kategori foto evidence'),
  ('evidence_photo_categories.update.all', 'Update Evidence Photo Categories', 'evidence_photo_categories', 'update', 'all', 'Mengubah kategori foto evidence'),
  ('evidence_photo_categories.delete.all', 'Delete Evidence Photo Categories', 'evidence_photo_categories', 'delete', 'all', 'Menonaktifkan kategori foto evidence'),
  ('inspection_recommendations.view.all', 'View Inspection Recommendations', 'inspection_recommendations', 'view', 'all', 'Melihat rekomendasi hasil pemeriksaan'),
  ('inspection_recommendations.create.all', 'Create Inspection Recommendations', 'inspection_recommendations', 'create', 'all', 'Membuat rekomendasi hasil pemeriksaan'),
  ('inspection_recommendations.update.all', 'Update Inspection Recommendations', 'inspection_recommendations', 'update', 'all', 'Mengubah rekomendasi hasil pemeriksaan'),
  ('inspection_recommendations.delete.all', 'Delete Inspection Recommendations', 'inspection_recommendations', 'delete', 'all', 'Menonaktifkan rekomendasi hasil pemeriksaan'),
  ('authorized_signers.view.all', 'View Authorized Signers', 'authorized_signers', 'view', 'all', 'Melihat pejabat penandatangan'),
  ('authorized_signers.create.all', 'Create Authorized Signers', 'authorized_signers', 'create', 'all', 'Membuat pejabat penandatangan'),
  ('authorized_signers.update.all', 'Update Authorized Signers', 'authorized_signers', 'update', 'all', 'Mengubah pejabat penandatangan'),
  ('authorized_signers.delete.all', 'Delete Authorized Signers', 'authorized_signers', 'delete', 'all', 'Menonaktifkan pejabat penandatangan'),
  ('company_profiles.view.all', 'View Company Profiles', 'company_profiles', 'view', 'all', 'Melihat profil badan usaha'),
  ('company_profiles.create.all', 'Create Company Profiles', 'company_profiles', 'create', 'all', 'Membuat profil badan usaha'),
  ('company_profiles.update.all', 'Update Company Profiles', 'company_profiles', 'update', 'all', 'Mengubah profil badan usaha'),
  ('company_profiles.delete.all', 'Delete Company Profiles', 'company_profiles', 'delete', 'all', 'Menonaktifkan profil badan usaha');

INSERT IGNORE INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
  'maintenance_schemes.view.all',
  'maintenance_schemes.create.all',
  'maintenance_schemes.update.all',
  'maintenance_schemes.delete.all',
  'inspection_areas.view.all',
  'inspection_areas.create.all',
  'inspection_areas.update.all',
  'inspection_areas.delete.all',
  'structural_components.view.all',
  'structural_components.create.all',
  'structural_components.update.all',
  'structural_components.delete.all',
  'structural_damage_criteria.view.all',
  'structural_damage_criteria.create.all',
  'structural_damage_criteria.update.all',
  'structural_damage_criteria.delete.all',
  'finding_severities.view.all',
  'finding_severities.create.all',
  'finding_severities.update.all',
  'finding_severities.delete.all',
  'inspection_test_parameters.view.all',
  'inspection_test_parameters.create.all',
  'inspection_test_parameters.update.all',
  'inspection_test_parameters.delete.all',
  'fitness_checklist_templates.view.all',
  'fitness_checklist_templates.create.all',
  'fitness_checklist_templates.update.all',
  'fitness_checklist_templates.delete.all',
  'evidence_photo_categories.view.all',
  'evidence_photo_categories.create.all',
  'evidence_photo_categories.update.all',
  'evidence_photo_categories.delete.all',
  'inspection_recommendations.view.all',
  'inspection_recommendations.create.all',
  'inspection_recommendations.update.all',
  'inspection_recommendations.delete.all',
  'authorized_signers.view.all',
  'authorized_signers.create.all',
  'authorized_signers.update.all',
  'authorized_signers.delete.all',
  'company_profiles.view.all',
  'company_profiles.create.all',
  'company_profiles.update.all',
  'company_profiles.delete.all'
)
WHERE r.code IN ('super_admin', 'admin');

COMMIT;